#
# Apollo Platform Makefile
#

obj-$(CONFIG_SMP)		+= headsmp.o platsmp.o
obj-$(CONFIG_HOTPLUG_CPU)	+= hotplug.o
obj-$(CONFIG_ARCH_APOLLO)	+= apollo84xx.o pll.o timer.o
obj-$(CONFIG_MACH_APOLLO)	+= apollo.o restart.o
