#
# Kronos Platform Makefile
#

obj-$(CONFIG_SMP)		+= headsmp.o platsmp.o
obj-$(CONFIG_HOTPLUG_CPU)	+= hotplug.o
obj-$(CONFIG_ARCH_KRONOS)	+= kronos1xx.o globaltimer.o pll.o
obj-$(CONFIG_MACH_KRONOS)	+= kronos.o restart.o
